MODULE ELTDATA_MOD

USE PARKIND1, ONLY : JPRB

IMPLICIT NONE

REAL(KIND=JPRB), ALLOCATABLE, SAVE, TARGET :: ZVODI_PERM (:,:,:)
REAL(KIND=JPRB), ALLOCATABLE, SAVE, TARGET :: ZFFT_PERM (:,:,:)
END MODULE

